### PR TITLE
Update modDesc.xml

### PR DESCRIPTION
**Pull request by Gonimy-Vetrom**

### CODE REVIEW

**Comment by TyKonKet** [comment]
Hi, for building the folder or the zip I use a script that bring all files in the main folder, then, the original paths were correct.

**Comment by Gonimy-Vetrom** [comment]
And ordinary users download without a script and get an error.

**Comment by TyKonKet** [comment]
Take a look at https://github.com/TyKonKet/FS17_CreatorTools/blob/master/build.cmd and https://github.com/TyKonKet/FS17_CreatorTools/blob/master/publish.cmd

**Comment by Gonimy-Vetrom** [comment]
I did not know that.

**Comment by Gonimy-Vetrom** [comment]
I have always enjoyed the means git.

**Comment by TyKonKet** [comment]
Ok then in your opinion I should use your way and change the publish and build scripts?

**Comment by Gonimy-Vetrom** [comment]
Maybe yes. Otherwise, it will come new translator (like me), then download the latest version and will receive an error.

**Comment by TyKonKet** [comment]
Ok, thank you for suggestion, I will do it.

**Pull request merged**
